In [40]:
import pandas as pd
from faker import Faker
import os
import random
from datetime import timedelta


fake = Faker()

In [24]:
df1 = pd.read_csv(r'N:\DE\CC Transaction Pipeline\source\fraudTrain.csv')
df1.columns
df1

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,1296670,2020-06-21 12:12:08,30263540414123,fraud_Reichel Inc,entertainment,15.56,Erik,Patterson,M,162 Jessica Row Apt. 072,...,37.7175,-112.4777,258,Geoscientist,1961-11-24,440b587732da4dc1a6395aba5fb41669,1371816728,36.841266,-111.690765,0
1296671,1296671,2020-06-21 12:12:19,6011149206456997,fraud_Abernathy and Sons,food_dining,51.70,Jeffrey,White,M,8617 Holmes Terrace Suite 651,...,39.2667,-77.5101,100,"Production assistant, television",1979-12-11,278000d2e0d2277d1de2f890067dcc0a,1371816739,38.906881,-78.246528,0
1296672,1296672,2020-06-21 12:12:32,3514865930894695,fraud_Stiedemann Ltd,food_dining,105.93,Christopher,Castaneda,M,1632 Cohen Drive Suite 639,...,32.9396,-105.8189,899,Naval architect,1967-08-30,483f52fe67fabef353d552c1e662974c,1371816752,33.619513,-105.130529,0
1296673,1296673,2020-06-21 12:13:36,2720012583106919,"fraud_Reinger, Weissnat and Strosin",food_dining,74.90,Joseph,Murray,M,42933 Ryan Underpass,...,43.3526,-102.5411,1126,Volunteer coordinator,1980-08-18,d667cdcbadaaed3da3f4020e83591c83,1371816816,42.788940,-103.241160,0
1296674,1296674,2020-06-21 12:13:37,4292902571056973207,"fraud_Langosh, Wintheiser and Hyatt",food_dining,4.30,Jeffrey,Smith,M,135 Joseph Mountains,...,45.8433,-113.8748,218,"Therapist, horticultural",1995-08-16,8f7c8e4ab7f25875d753b422917c98c9,1371816817,46.565983,-114.186110,0

In [25]:
df2 = pd.read_csv(r'N:\DE\CC Transaction Pipeline\source\fraudTest.csv')
df2.columns
df2

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,555714,2020-12-31 23:59:07,30560609640617,fraud_Reilly and Sons,health_fitness,43.77,Michael,Olson,M,558 Michael Estates,...,40.4931,-91.8912,519,Town planner,1966-02-13,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,-91.333331,0
555715,555715,2020-12-31 23:59:09,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.84,Jose,Vasquez,M,572 Davis Mountains,...,29.0393,-95.4401,28739,Futures trader,1999-12-27,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,-96.186633,0
555716,555716,2020-12-31 23:59:15,6011724471098086,fraud_Rau-Robel,kids_pets,86.88,Ann,Lawson,F,144 Evans Islands Apt. 683,...,46.1966,-118.9017,3684,Musician,1981-11-29,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,-119.715054,0
555717,555717,2020-12-31 23:59:24,4079773899158,fraud_Breitenberg LLC,travel,7.99,Eric,Preston,M,7020 Doyle Stream Apt. 951,...,44.6255,-116.4493,129,Cartographer,1965-12-15,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,-117.080888,0
555718,555718,2020-12-31 23:59:34,4170689372027579,fraud_Dare-Marvin,entertainment,38.13,Samuel,Frey,M,830 Myers Plaza Apt. 384,...,35.6665,-97.4798,116001,Media buyer,1993-05-10,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,-97.036372,0

In [29]:
df = pd.concat([df1,df2])
df = df.drop(df.columns[0],axis=1)
df = df.drop_duplicates()
df

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,2020-12-31 23:59:07,30560609640617,fraud_Reilly and Sons,health_fitness,43.77,Michael,Olson,M,558 Michael Estates,Luray,...,40.4931,-91.8912,519,Town planner,1966-02-13,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,-91.333331,0
555715,2020-12-31 23:59:09,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.84,Jose,Vasquez,M,572 Davis Mountains,Lake Jackson,...,29.0393,-95.4401,28739,Futures trader,1999-12-27,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,-96.186633,0
555716,2020-12-31 23:59:15,6011724471098086,fraud_Rau-Robel,kids_pets,86.88,Ann,Lawson,F,144 Evans Islands Apt. 683,Burbank,...,46.1966,-118.9017,3684,Musician,1981-11-29,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,-119.715054,0
555717,2020-12-31 23:59:24,4079773899158,fraud_Breitenberg LLC,travel,7.99,Eric,Preston,M,7020 Doyle Stream Apt. 951,Mesa,...,44.6255,-116.4493,129,Cartographer,1965-12-15,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,-117.080888,0
555718,2020-12-31 23:59:34,4170689372027579,fraud_Dare-Marvin,entertainment,38.13,Samuel,Frey,M,830 Myers Plaza Apt. 384,Edmond,...,35.6665,-97.4798,116001,Media buyer,1993-05-10,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,-97.036372,0

Dim Customers

In [56]:
df_cust = df[['cc_num', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat', 'long', 'city_pop', 'job', 'dob']].drop_duplicates().copy()
# df_cust.head()
len(df_cust)

999

In [57]:
len(df_cust['cc_num'].unique()) 
#observed 999 unique cc_nums and corresponding 999 unique customer details

999

In [58]:
len(df_cust[['first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat', 'long', 'city_pop', 'job', 'dob']].drop_duplicates())

999

In [59]:
df_cust['cust_uuid'] = [fake.unique.uuid4() for _ in range(len(df_cust))]
# df_cust = df_cust.drop('cc_num',axis=1)
len(df_cust)

999

In [62]:
len(df_cust['cust_uuid'].unique())

999

In [60]:
df_cust.head()

,cc_num,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,cust_uuid
0,2703186189652095,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,NC,28654,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,9e7a735c-3f0a-458a-ab3a-fdf2dae57a02
1,630423337322,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,WA,99160,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,bc827667-874b-410d-a5f2-f7b48063dd85
2,38859492057661,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,ID,83252,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,fbe99ed9-9b7e-4980-a5a7-42a18834af9b
3,3534093764340240,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,MT,59632,46.2306,-112.1138,1939,Patent attorney,1967-01-12,cb98b16b-31c7-487b-b959-342c9695a189
4,375534208663984,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,VA,24433,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,efea4589-9abd-4051-aac2-da76c1751f9b

Dim Merchant

In [34]:
df_merc = df[['merchant', 'merch_lat', 'merch_long']].drop_duplicates().copy()
# df_merc.head()
len(df_merc)

1852394

In [35]:
len(df_merc['merchant'].unique())

693

In [36]:
df_sorted = df.sort_values(by=['merchant', 'trans_date_trans_time'], ascending=[True, False])
df_merc = df_sorted.drop_duplicates(subset='merchant', keep='first')
df_merc = df_merc[['merchant', 'merch_lat', 'merch_long']].copy()
len(df_merc)

693

In [37]:
df_merc['merch_uuid'] = [fake.unique.uuid4() for _ in range(len(df_merc))]
len(df_merc)

693

In [38]:
df_merc

,merchant,merch_lat,merch_long,merch_uuid
554883,fraud_Abbott-Rogahn,26.460232,-83.062399,e69dab83-7048-431e-b47f-f9e6d3711d28
555352,fraud_Abbott-Steuber,31.218339,-81.606691,8bf09c70-722c-4352-aa00-b9ff64418776
555038,fraud_Abernathy and Sons,45.384730,-121.637729,ea2aee2a-07c5-4abc-af9d-f255da5e2560
555153,fraud_Abshire PLC,37.627680,-96.249890,c8cb187c-1790-48b5-ae61-0502ec81aa60
553623,"fraud_Adams, Kovacek and Kuhlman",49.807705,-117.388555,6763b544-54f4-4d33-a745-71b6ae9dbc1a
...,...,...,...,...
553030,fraud_Zemlak Group,37.395201,-123.189612,96f7cce3-4016-4003-b059-fb5285e47ab4
555295,"fraud_Zemlak, Tillman and Cremin",40.351438,-78.903120,dccc8831-7cb1-4824-8143-db24721c113a
554983,fraud_Ziemann-Waters,37.933006,-122.090075,7942b9c0-19d9-49c5-87ac-ff7f377368ca
553539,"fraud_Zieme, Bode and Dooley",38.341098,-89.059213,80ef29a7-b8b7-46a6-a8db-bb1becfad0c7
555059,fraud_Zulauf LLC,39.565478,-82.763677,597c20de-a9de-45af-96a5-4b50db582a0b

Dim card

In [47]:
df_card = df[['cc_num']].drop_duplicates().copy()
len(df_card)

999

In [48]:
import numpy as np

def get_category_limit(category):
    
    tiers = {
        'Basic':     {'range': (1000, 5000),   'step': 500},
        'Gold':      {'range': (5000, 15000),  'step': 1000},
        'Platinum':  {'range': (15000, 30000), 'step': 2500},
        'Signature': {'range': (30000, 50000), 'step': 5000},
        'Infinite':  {'range': (50000, 100000),'step': 10000}
    }
    
    config = tiers.get(category)
    
    limit = random.randrange(config['range'][0], config['range'][1] + 1, config['step'])
    return limit

In [49]:
def generate_card_details(row):
    card_provider = fake.credit_card_provider()
    
    category = random.choice(['Basic', 'Gold', 'Platinum', 'Signature', 'Infinite'])
    
    issue_date = fake.date_between(start_date='-5y', end_date='today')
    
    expiry_years = random.randint(3, 5)
    expiration_date = issue_date + timedelta(days=expiry_years * 365)
    
    limit = get_category_limit(category)
    
    return pd.Series([card_provider, category, expiration_date, issue_date, limit])

df_card[['card_provider', 'card_category', 'expiration_date', 'issue_date', 'credit_limit']] = df_card.apply(generate_card_details, axis=1)

In [50]:
df_card

,cc_num,card_provider,card_category,expiration_date,issue_date,credit_limit
0,2703186189652095,VISA 16 digit,Infinite,2026-11-23,2023-11-24,70000
1,630423337322,VISA 13 digit,Platinum,2026-03-09,2023-03-10,15000
2,38859492057661,American Express,Platinum,2026-03-10,2022-03-11,27500
3,3534093764340240,VISA 19 digit,Gold,2026-07-27,2023-07-28,10000
4,375534208663984,JCB 16 digit,Signature,2028-08-11,2025-08-12,45000
...,...,...,...,...,...,...
327231,4883407061576,Mastercard,Basic,2029-08-29,2024-08-30,2500
328127,4295296907373,VISA 19 digit,Gold,2027-05-07,2023-05-08,10000
342954,4087542780207162,JCB 16 digit,Signature,2030-04-11,2026-04-12,50000
422405,3588001568691267,VISA 16 digit,Infinite,2030-01-23,2026-01-24,70000
506021,2242176657877538,JCB 16 digit,Gold,2026-03-29,2023-03-30,9000

Fact revamp

In [52]:
df_joined = pd.merge(df, df_merc[['merchant','merch_uuid']], on='merchant', how='left')
df_joined

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,...,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,merch_uuid
0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,...,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0,ae1209cd-87ee-475f-9bcc-8e3ae46031de
1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,...,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0,8aff85dd-5e45-4ee2-8403-97b1550f013f
2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,...,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0,b1c8a9b1-a417-468c-8a4f-0964da73d31d
3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,...,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0,9b1a10cd-f6c7-4f0f-b449-0eb07d271030
4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,...,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0,39d11ec4-1c4f-41f3-a5b8-12bc1899910b
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1852389,2020-12-31 23:59:07,30560609640617,fraud_Reilly and Sons,health_fitness,43.77,Michael,Olson,M,558 Michael Estates,Luray,...,-91.8912,519,Town planner,1966-02-13,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,-91.333331,0,efa46b96-1f90-45db-a8e1-dff64e0b11e6
1852390,2020-12-31 23:59:09,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.84,Jose,Vasquez,M,572 Davis Mountains,Lake Jackson,...,-95.4401,28739,Futures trader,1999-12-27,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,-96.186633,0,39bde5fe-58ff-4f9c-9534-35df72df10f3
1852391,2020-12-31 23:59:15,6011724471098086,fraud_Rau-Robel,kids_pets,86.88,Ann,Lawson,F,144 Evans Islands Apt. 683,Burbank,...,-118.9017,3684,Musician,1981-11-29,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,-119.715054,0,1642da8b-10be-461f-8936-a349766f7445
1852392,2020-12-31 23:59:24,4079773899158,fraud_Breitenberg LLC,travel,7.99,Eric,Preston,M,7020 Doyle Stream Apt. 951,Mesa,...,-116.4493,129,Cartographer,1965-12-15,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,-117.080888,0,57649223-d6c6-4421-aecc-798eeddd31d8
1852393,2020-12-31 23:59:34,4170689372027579,fraud_Dare-Marvin,entertainment,38.13,Samuel,Frey,M,830 Myers Plaza Apt. 384,Edmond,...,-97.4798,116001,Media buyer,1993-05-10,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,-97.036372,0,8dce1ce7-daba-4f35-ab34-b05ac3e817bd

In [61]:
df_joined = pd.merge(df_joined, df_cust[['cc_num','cust_uuid']], on='cc_num', how='left')
df_joined

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,...,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,merch_uuid,cust_uuid
0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,...,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0,ae1209cd-87ee-475f-9bcc-8e3ae46031de,9e7a735c-3f0a-458a-ab3a-fdf2dae57a02
1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,...,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0,8aff85dd-5e45-4ee2-8403-97b1550f013f,bc827667-874b-410d-a5f2-f7b48063dd85
2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,...,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0,b1c8a9b1-a417-468c-8a4f-0964da73d31d,fbe99ed9-9b7e-4980-a5a7-42a18834af9b
3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,...,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0,9b1a10cd-f6c7-4f0f-b449-0eb07d271030,cb98b16b-31c7-487b-b959-342c9695a189
4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,...,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0,39d11ec4-1c4f-41f3-a5b8-12bc1899910b,efea4589-9abd-4051-aac2-da76c1751f9b
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1852389,2020-12-31 23:59:07,30560609640617,fraud_Reilly and Sons,health_fitness,43.77,Michael,Olson,M,558 Michael Estates,Luray,...,519,Town planner,1966-02-13,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,-91.333331,0,efa46b96-1f90-45db-a8e1-dff64e0b11e6,11f782e0-33db-4395-aec3-a8cf72278530
1852390,2020-12-31 23:59:09,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.84,Jose,Vasquez,M,572 Davis Mountains,Lake Jackson,...,28739,Futures trader,1999-12-27,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,-96.186633,0,39bde5fe-58ff-4f9c-9534-35df72df10f3,9f8b84fe-b14b-4e3d-b454-986166afce3f
1852391,2020-12-31 23:59:15,6011724471098086,fraud_Rau-Robel,kids_pets,86.88,Ann,Lawson,F,144 Evans Islands Apt. 683,Burbank,...,3684,Musician,1981-11-29,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,-119.715054,0,1642da8b-10be-461f-8936-a349766f7445,f1346b82-ff62-406b-9dc3-6d2fec49485e
1852392,2020-12-31 23:59:24,4079773899158,fraud_Breitenberg LLC,travel,7.99,Eric,Preston,M,7020 Doyle Stream Apt. 951,Mesa,...,129,Cartographer,1965-12-15,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,-117.080888,0,57649223-d6c6-4421-aecc-798eeddd31d8,9df628c0-b154-4e89-9084-bf0eb8e774c8
1852393,2020-12-31 23:59:34,4170689372027579,fraud_Dare-Marvin,entertainment,38.13,Samuel,Frey,M,830 Myers Plaza Apt. 384,Edmond,...,116001,Media buyer,1993-05-10,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,-97.036372,0,8dce1ce7-daba-4f35-ab34-b05ac3e817bd,e2549e0f-44e4-497f-8d51-ebaf1ad9fb43

In [66]:
df_joined.columns

Index(['trans_date_trans_time', 'cc_num', 'merchant', 'category', 'amt',
       'first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat',
       'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time', 'merch_lat',
       'merch_long', 'is_fraud', 'merch_uuid', 'cust_uuid'],
      dtype='str')

In [ ]:
final_df = df_joined[['trans_num', 'merch_uuid', 'cust_uuid', 'trans_date_trans_time', 'cc_num', 'category', 'amt', 'unix_time', 'is_fraud']].copy()

Write to csv

In [63]:
df_cust = df_cust.drop('cc_num',axis=1)
df_cust

,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,cust_uuid
0,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,NC,28654,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,9e7a735c-3f0a-458a-ab3a-fdf2dae57a02
1,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,WA,99160,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,bc827667-874b-410d-a5f2-f7b48063dd85
2,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,ID,83252,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,fbe99ed9-9b7e-4980-a5a7-42a18834af9b
3,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,MT,59632,46.2306,-112.1138,1939,Patent attorney,1967-01-12,cb98b16b-31c7-487b-b959-342c9695a189
4,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,VA,24433,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,efea4589-9abd-4051-aac2-da76c1751f9b
...,...,...,...,...,...,...,...,...,...,...,...,...,...
327231,Rachel,Williams,F,6386 Bailey Hill Apt. 421,Seattle,WA,98118,47.5412,-122.2750,837792,Systems developer,1936-12-23,17a9d9ed-8d5b-4674-a9f0-c403676739f8
328127,Destiny,Fowler,F,007 Tonya Isle Suite 299,Wever,IA,52658,40.7067,-91.2268,1071,Quantity surveyor,1998-08-02,0edcccc8-0b54-4f19-be1e-1e7c5683c016
342954,Nicole,Dominguez,F,537 Brian Island,Guthrie,OK,73044,35.8330,-97.4360,20226,Retail manager,1969-11-08,4c54c3fd-8dfb-4939-99d9-36c2eb9ecc20
422405,Jason,Johnson,M,5942 Thomas Park,Craig,AK,99921,55.4732,-133.1171,1920,Commissioning editor,1997-06-17,0b8128c0-57e0-4cb6-9f66-c1dda98ce4f4
506021,Travis,Daniel,M,1327 Rose Causeway Apt. 610,Senatobia,MS,38668,34.6323,-89.8855,14462,Database administrator,1959-03-03,1aad847a-ca43-4c26-bfce-9a7e63fb55c5

In [ ]:
df_cust.to_csv(r'N:\DE\CC Transaction Pipeline\landing\dim_customer.csv',index=False)
df_merc.to_csv(r'N:\DE\CC Transaction Pipeline\landing\dim_merchant.csv',index=False)
df_card.to_csv(r'N:\DE\CC Transaction Pipeline\landing\dim_card.csv',index=False)
final_df.to_csv(r'N:\DE\CC Transaction Pipeline\landing\fact_transactions.csv',index=False)